/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearRolloverRouteImport } from './routes/year-rollover'
import { Route as TimetableConfigRouteImport } from './routes/timetable-config'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as TenantRoleMenuRouteImport } from './routes/tenant-role-menu'
import { Route as TenantFormRouteImport } from './routes/tenant-form'
import { Route as TeacherWorkloadRouteImport } from './routes/teacher-workload'
import { Route as SyllabusTrackerRouteImport } from './routes/syllabus-tracker'
import { Route as SubstituteTeacherPoolRouteImport } from './routes/substitute-teacher-pool'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SubjectsCurriculumRouteImport } from './routes/subjects-curriculum'
import { Route as SubjectAllocationRouteImport } from './routes/subject-allocation'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentLifeDevelopmentRouteImport } from './routes/student-life-development'
import { Route as StudentIdConfigRouteImport } from './routes/student-id-config'
import { Route as StudentEditRouteImport } from './routes/student-edit'
import { Route as StudentDetailRouteImport } from './routes/student-detail'
import { Route as StudentAddRouteImport } from './routes/student-add'
import { Route as StaffSetupRouteImport } from './routes/staff-setup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SchoolCalendarRouteImport } from './routes/school-calendar'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as RolePermissionsRouteImport } from './routes/role-permissions'
import { Route as RoleMenuRouteImport } from './routes/role-menu'
import { Route as ReportsClassicRouteImport } from './routes/reports-classic'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportViewerRouteImport } from './routes/report-viewer'
import { Route as ReportConfigEditRouteImport } from './routes/report-config-edit'
import { Route as ReportConfigRouteImport } from './routes/report-config'
import { Route as PromotionRulesRouteImport } from './routes/promotion-rules'
import { Route as PeriodStructureSetupRouteImport } from './routes/period-structure-setup'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonPlansRouteImport } from './routes/lesson-plans'
import { Route as LearningOutcomesRouteImport } from './routes/learning-outcomes'
import { Route as GradingScaleRouteImport } from './routes/grading-scale'
import { Route as GovernanceDashboardRouteImport } from './routes/governance-dashboard'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as FeeConfigurationRouteImport } from './routes/fee-configuration'
import { Route as ExaminationsRouteImport } from './routes/examinations'
import { Route as ExamDetailRouteImport } from './routes/exam-detail'
import { Route as ExamCorrectionsRouteImport } from './routes/exam-corrections'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as DocumentNumberingRouteImport } from './routes/document-numbering'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DateFormatRouteImport } from './routes/date-format'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurriculumMappingRouteImport } from './routes/curriculum-mapping'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CommunicationSettingsRouteImport } from './routes/communication-settings'
import { Route as ClassesSectionsRouteImport } from './routes/classes-sections'
import { Route as ClassTeacherAllocationRouteImport } from './routes/class-teacher-allocation'
import { Route as CampusSetupRouteImport } from './routes/campus-setup'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AttendanceRequestsRouteImport } from './routes/attendance-requests'
import { Route as AttendancePolicyRouteImport } from './routes/attendance-policy'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AkiraUserListRouteImport } from './routes/akira-user-list'
import { Route as AdmissionsTestsRouteImport } from './routes/admissions-tests'
import { Route as AdmissionsInquiryFormRouteImport } from './routes/admissions-inquiry-form'
import { Route as AdmissionsInquiriesRouteImport } from './routes/admissions-inquiries'
import { Route as AdmissionsApplicationsRouteImport } from './routes/admissions-applications'
import { Route as AdmissionsApplicationFormRouteImport } from './routes/admissions-application-form'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AcademicPolicySettingsRouteImport } from './routes/academic-policy-settings'
import { Route as AcademicHealthDashboardRouteImport } from './routes/academic-health-dashboard'
import { Route as AcademicCoordinatorDashboardRouteImport } from './routes/academic-coordinator-dashboard'
import { Route as AcademicCalendarRouteImport } from './routes/academic-calendar'
import { Route as IndexRouteImport } from './routes/index'

const YearRolloverRoute = YearRolloverRouteImport.update({
  id: '/year-rollover',
  path: '/year-rollover',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableConfigRoute = TimetableConfigRouteImport.update({
  id: '/timetable-config',
  path: '/timetable-config',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoleMenuRoute = TenantRoleMenuRouteImport.update({
  id: '/tenant-role-menu',
  path: '/tenant-role-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantFormRoute = TenantFormRouteImport.update({
  id: '/tenant-form',
  path: '/tenant-form',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherWorkloadRoute = TeacherWorkloadRouteImport.update({
  id: '/teacher-workload',
  path: '/teacher-workload',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusTrackerRoute = SyllabusTrackerRouteImport.update({
  id: '/syllabus-tracker',
  path: '/syllabus-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstituteTeacherPoolRoute = SubstituteTeacherPoolRouteImport.update({
  id: '/substitute-teacher-pool',
  path: '/substitute-teacher-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsCurriculumRoute = SubjectsCurriculumRouteImport.update({
  id: '/subjects-curriculum',
  path: '/subjects-curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectAllocationRoute = SubjectAllocationRouteImport.update({
  id: '/subject-allocation',
  path: '/subject-allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeDevelopmentRoute = StudentLifeDevelopmentRouteImport.update({
  id: '/student-life-development',
  path: '/student-life-development',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIdConfigRoute = StudentIdConfigRouteImport.update({
  id: '/student-id-config',
  path: '/student-id-config',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEditRoute = StudentEditRouteImport.update({
  id: '/student-edit',
  path: '/student-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDetailRoute = StudentDetailRouteImport.update({
  id: '/student-detail',
  path: '/student-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAddRoute = StudentAddRouteImport.update({
  id: '/student-add',
  path: '/student-add',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSetupRoute = StaffSetupRouteImport.update({
  id: '/staff-setup',
  path: '/staff-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolCalendarRoute = SchoolCalendarRouteImport.update({
  id: '/school-calendar',
  path: '/school-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const RolePermissionsRoute = RolePermissionsRouteImport.update({
  id: '/role-permissions',
  path: '/role-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleMenuRoute = RoleMenuRouteImport.update({
  id: '/role-menu',
  path: '/role-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsClassicRoute = ReportsClassicRouteImport.update({
  id: '/reports-classic',
  path: '/reports-classic',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportViewerRoute = ReportViewerRouteImport.update({
  id: '/report-viewer',
  path: '/report-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportConfigEditRoute = ReportConfigEditRouteImport.update({
  id: '/report-config-edit',
  path: '/report-config-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportConfigRoute = ReportConfigRouteImport.update({
  id: '/report-config',
  path: '/report-config',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionRulesRoute = PromotionRulesRouteImport.update({
  id: '/promotion-rules',
  path: '/promotion-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodStructureSetupRoute = PeriodStructureSetupRouteImport.update({
  id: '/period-structure-setup',
  path: '/period-structure-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPlansRoute = LessonPlansRouteImport.update({
  id: '/lesson-plans',
  path: '/lesson-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningOutcomesRoute = LearningOutcomesRouteImport.update({
  id: '/learning-outcomes',
  path: '/learning-outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingScaleRoute = GradingScaleRouteImport.update({
  id: '/grading-scale',
  path: '/grading-scale',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceDashboardRoute = GovernanceDashboardRouteImport.update({
  id: '/governance-dashboard',
  path: '/governance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeConfigurationRoute = FeeConfigurationRouteImport.update({
  id: '/fee-configuration',
  path: '/fee-configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsRoute = ExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamDetailRoute = ExamDetailRouteImport.update({
  id: '/exam-detail',
  path: '/exam-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCorrectionsRoute = ExamCorrectionsRouteImport.update({
  id: '/exam-corrections',
  path: '/exam-corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentNumberingRoute = DocumentNumberingRouteImport.update({
  id: '/document-numbering',
  path: '/document-numbering',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DateFormatRoute = DateFormatRouteImport.update({
  id: '/date-format',
  path: '/date-format',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumMappingRoute = CurriculumMappingRouteImport.update({
  id: '/curriculum-mapping',
  path: '/curriculum-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationSettingsRoute = CommunicationSettingsRouteImport.update({
  id: '/communication-settings',
  path: '/communication-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSectionsRoute = ClassesSectionsRouteImport.update({
  id: '/classes-sections',
  path: '/classes-sections',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassTeacherAllocationRoute = ClassTeacherAllocationRouteImport.update({
  id: '/class-teacher-allocation',
  path: '/class-teacher-allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusSetupRoute = CampusSetupRouteImport.update({
  id: '/campus-setup',
  path: '/campus-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRequestsRoute = AttendanceRequestsRouteImport.update({
  id: '/attendance-requests',
  path: '/attendance-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendancePolicyRoute = AttendancePolicyRouteImport.update({
  id: '/attendance-policy',
  path: '/attendance-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AkiraUserListRoute = AkiraUserListRouteImport.update({
  id: '/akira-user-list',
  path: '/akira-user-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsTestsRoute = AdmissionsTestsRouteImport.update({
  id: '/admissions-tests',
  path: '/admissions-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsInquiryFormRoute = AdmissionsInquiryFormRouteImport.update({
  id: '/admissions-inquiry-form',
  path: '/admissions-inquiry-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsInquiriesRoute = AdmissionsInquiriesRouteImport.update({
  id: '/admissions-inquiries',
  path: '/admissions-inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplicationsRoute = AdmissionsApplicationsRouteImport.update({
  id: '/admissions-applications',
  path: '/admissions-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplicationFormRoute =
  AdmissionsApplicationFormRouteImport.update({
    id: '/admissions-application-form',
    path: '/admissions-application-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPolicySettingsRoute = AcademicPolicySettingsRouteImport.update({
  id: '/academic-policy-settings',
  path: '/academic-policy-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicHealthDashboardRoute = AcademicHealthDashboardRouteImport.update({
  id: '/academic-health-dashboard',
  path: '/academic-health-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCoordinatorDashboardRoute =
  AcademicCoordinatorDashboardRouteImport.update({
    id: '/academic-coordinator-dashboard',
    path: '/academic-coordinator-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-coordinator-dashboard': typeof AcademicCoordinatorDashboardRoute
  '/academic-health-dashboard': typeof AcademicHealthDashboardRoute
  '/academic-policy-settings': typeof AcademicPolicySettingsRoute
  '/academics': typeof AcademicsRoute
  '/admissions-application-form': typeof AdmissionsApplicationFormRoute
  '/admissions-applications': typeof AdmissionsApplicationsRoute
  '/admissions-inquiries': typeof AdmissionsInquiriesRoute
  '/admissions-inquiry-form': typeof AdmissionsInquiryFormRoute
  '/admissions-tests': typeof AdmissionsTestsRoute
  '/akira-user-list': typeof AkiraUserListRoute
  '/attendance': typeof AttendanceRoute
  '/attendance-policy': typeof AttendancePolicyRoute
  '/attendance-requests': typeof AttendanceRequestsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/calendar': typeof CalendarRoute
  '/campus-setup': typeof CampusSetupRoute
  '/class-teacher-allocation': typeof ClassTeacherAllocationRoute
  '/classes-sections': typeof ClassesSectionsRoute
  '/communication-settings': typeof CommunicationSettingsRoute
  '/components': typeof ComponentsRoute
  '/curriculum-mapping': typeof CurriculumMappingRoute
  '/dashboard': typeof DashboardRoute
  '/date-format': typeof DateFormatRoute
  '/departments': typeof DepartmentsRoute
  '/document-numbering': typeof DocumentNumberingRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/exam-corrections': typeof ExamCorrectionsRoute
  '/exam-detail': typeof ExamDetailRoute
  '/examinations': typeof ExaminationsRoute
  '/fee-configuration': typeof FeeConfigurationRoute
  '/fees': typeof FeesRoute
  '/governance-dashboard': typeof GovernanceDashboardRoute
  '/grading-scale': typeof GradingScaleRoute
  '/learning-outcomes': typeof LearningOutcomesRoute
  '/lesson-plans': typeof LessonPlansRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/period-structure-setup': typeof PeriodStructureSetupRoute
  '/promotion-rules': typeof PromotionRulesRoute
  '/report-config': typeof ReportConfigRoute
  '/report-config-edit': typeof ReportConfigEditRoute
  '/report-viewer': typeof ReportViewerRoute
  '/reports': typeof ReportsRoute
  '/reports-classic': typeof ReportsClassicRoute
  '/role-menu': typeof RoleMenuRoute
  '/role-permissions': typeof RolePermissionsRoute
  '/roles': typeof RolesRoute
  '/school-calendar': typeof SchoolCalendarRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/staff-setup': typeof StaffSetupRoute
  '/student-add': typeof StudentAddRoute
  '/student-detail': typeof StudentDetailRoute
  '/student-edit': typeof StudentEditRoute
  '/student-id-config': typeof StudentIdConfigRoute
  '/student-life-development': typeof StudentLifeDevelopmentRoute
  '/students': typeof StudentsRoute
  '/subject-allocation': typeof SubjectAllocationRoute
  '/subjects-curriculum': typeof SubjectsCurriculumRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/substitute-teacher-pool': typeof SubstituteTeacherPoolRoute
  '/syllabus-tracker': typeof SyllabusTrackerRoute
  '/teacher-workload': typeof TeacherWorkloadRoute
  '/tenant-form': typeof TenantFormRoute
  '/tenant-role-menu': typeof TenantRoleMenuRoute
  '/tenants': typeof TenantsRoute
  '/timetable': typeof TimetableRoute
  '/timetable-config': typeof TimetableConfigRoute
  '/year-rollover': typeof YearRolloverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-coordinator-dashboard': typeof AcademicCoordinatorDashboardRoute
  '/academic-health-dashboard': typeof AcademicHealthDashboardRoute
  '/academic-policy-settings': typeof AcademicPolicySettingsRoute
  '/academics': typeof AcademicsRoute
  '/admissions-application-form': typeof AdmissionsApplicationFormRoute
  '/admissions-applications': typeof AdmissionsApplicationsRoute
  '/admissions-inquiries': typeof AdmissionsInquiriesRoute
  '/admissions-inquiry-form': typeof AdmissionsInquiryFormRoute
  '/admissions-tests': typeof AdmissionsTestsRoute
  '/akira-user-list': typeof AkiraUserListRoute
  '/attendance': typeof AttendanceRoute
  '/attendance-policy': typeof AttendancePolicyRoute
  '/attendance-requests': typeof AttendanceRequestsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/calendar': typeof CalendarRoute
  '/campus-setup': typeof CampusSetupRoute
  '/class-teacher-allocation': typeof ClassTeacherAllocationRoute
  '/classes-sections': typeof ClassesSectionsRoute
  '/communication-settings': typeof CommunicationSettingsRoute
  '/components': typeof ComponentsRoute
  '/curriculum-mapping': typeof CurriculumMappingRoute
  '/dashboard': typeof DashboardRoute
  '/date-format': typeof DateFormatRoute
  '/departments': typeof DepartmentsRoute
  '/document-numbering': typeof DocumentNumberingRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/exam-corrections': typeof ExamCorrectionsRoute
  '/exam-detail': typeof ExamDetailRoute
  '/examinations': typeof ExaminationsRoute
  '/fee-configuration': typeof FeeConfigurationRoute
  '/fees': typeof FeesRoute
  '/governance-dashboard': typeof GovernanceDashboardRoute
  '/grading-scale': typeof GradingScaleRoute
  '/learning-outcomes': typeof LearningOutcomesRoute
  '/lesson-plans': typeof LessonPlansRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/period-structure-setup': typeof PeriodStructureSetupRoute
  '/promotion-rules': typeof PromotionRulesRoute
  '/report-config': typeof ReportConfigRoute
  '/report-config-edit': typeof ReportConfigEditRoute
  '/report-viewer': typeof ReportViewerRoute
  '/reports': typeof ReportsRoute
  '/reports-classic': typeof ReportsClassicRoute
  '/role-menu': typeof RoleMenuRoute
  '/role-permissions': typeof RolePermissionsRoute
  '/roles': typeof RolesRoute
  '/school-calendar': typeof SchoolCalendarRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/staff-setup': typeof StaffSetupRoute
  '/student-add': typeof StudentAddRoute
  '/student-detail': typeof StudentDetailRoute
  '/student-edit': typeof StudentEditRoute
  '/student-id-config': typeof StudentIdConfigRoute
  '/student-life-development': typeof StudentLifeDevelopmentRoute
  '/students': typeof StudentsRoute
  '/subject-allocation': typeof SubjectAllocationRoute
  '/subjects-curriculum': typeof SubjectsCurriculumRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/substitute-teacher-pool': typeof SubstituteTeacherPoolRoute
  '/syllabus-tracker': typeof SyllabusTrackerRoute
  '/teacher-workload': typeof TeacherWorkloadRoute
  '/tenant-form': typeof TenantFormRoute
  '/tenant-role-menu': typeof TenantRoleMenuRoute
  '/tenants': typeof TenantsRoute
  '/timetable': typeof TimetableRoute
  '/timetable-config': typeof TimetableConfigRoute
  '/year-rollover': typeof YearRolloverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-coordinator-dashboard': typeof AcademicCoordinatorDashboardRoute
  '/academic-health-dashboard': typeof AcademicHealthDashboardRoute
  '/academic-policy-settings': typeof AcademicPolicySettingsRoute
  '/academics': typeof AcademicsRoute
  '/admissions-application-form': typeof AdmissionsApplicationFormRoute
  '/admissions-applications': typeof AdmissionsApplicationsRoute
  '/admissions-inquiries': typeof AdmissionsInquiriesRoute
  '/admissions-inquiry-form': typeof AdmissionsInquiryFormRoute
  '/admissions-tests': typeof AdmissionsTestsRoute
  '/akira-user-list': typeof AkiraUserListRoute
  '/attendance': typeof AttendanceRoute
  '/attendance-policy': typeof AttendancePolicyRoute
  '/attendance-requests': typeof AttendanceRequestsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/calendar': typeof CalendarRoute
  '/campus-setup': typeof CampusSetupRoute
  '/class-teacher-allocation': typeof ClassTeacherAllocationRoute
  '/classes-sections': typeof ClassesSectionsRoute
  '/communication-settings': typeof CommunicationSettingsRoute
  '/components': typeof ComponentsRoute
  '/curriculum-mapping': typeof CurriculumMappingRoute
  '/dashboard': typeof DashboardRoute
  '/date-format': typeof DateFormatRoute
  '/departments': typeof DepartmentsRoute
  '/document-numbering': typeof DocumentNumberingRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/exam-corrections': typeof ExamCorrectionsRoute
  '/exam-detail': typeof ExamDetailRoute
  '/examinations': typeof ExaminationsRoute
  '/fee-configuration': typeof FeeConfigurationRoute
  '/fees': typeof FeesRoute
  '/governance-dashboard': typeof GovernanceDashboardRoute
  '/grading-scale': typeof GradingScaleRoute
  '/learning-outcomes': typeof LearningOutcomesRoute
  '/lesson-plans': typeof LessonPlansRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/period-structure-setup': typeof PeriodStructureSetupRoute
  '/promotion-rules': typeof PromotionRulesRoute
  '/report-config': typeof ReportConfigRoute
  '/report-config-edit': typeof ReportConfigEditRoute
  '/report-viewer': typeof ReportViewerRoute
  '/reports': typeof ReportsRoute
  '/reports-classic': typeof ReportsClassicRoute
  '/role-menu': typeof RoleMenuRoute
  '/role-permissions': typeof RolePermissionsRoute
  '/roles': typeof RolesRoute
  '/school-calendar': typeof SchoolCalendarRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/staff-setup': typeof StaffSetupRoute
  '/student-add': typeof StudentAddRoute
  '/student-detail': typeof StudentDetailRoute
  '/student-edit': typeof StudentEditRoute
  '/student-id-config': typeof StudentIdConfigRoute
  '/student-life-development': typeof StudentLifeDevelopmentRoute
  '/students': typeof StudentsRoute
  '/subject-allocation': typeof SubjectAllocationRoute
  '/subjects-curriculum': typeof SubjectsCurriculumRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/substitute-teacher-pool': typeof SubstituteTeacherPoolRoute
  '/syllabus-tracker': typeof SyllabusTrackerRoute
  '/teacher-workload': typeof TeacherWorkloadRoute
  '/tenant-form': typeof TenantFormRoute
  '/tenant-role-menu': typeof TenantRoleMenuRoute
  '/tenants': typeof TenantsRoute
  '/timetable': typeof TimetableRoute
  '/timetable-config': typeof TimetableConfigRoute
  '/year-rollover': typeof YearRolloverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-calendar'
    | '/academic-coordinator-dashboard'
    | '/academic-health-dashboard'
    | '/academic-policy-settings'
    | '/academics'
    | '/admissions-application-form'
    | '/admissions-applications'
    | '/admissions-inquiries'
    | '/admissions-inquiry-form'
    | '/admissions-tests'
    | '/akira-user-list'
    | '/attendance'
    | '/attendance-policy'
    | '/attendance-requests'
    | '/audit-logs'
    | '/calendar'
    | '/campus-setup'
    | '/class-teacher-allocation'
    | '/classes-sections'
    | '/communication-settings'
    | '/components'
    | '/curriculum-mapping'
    | '/dashboard'
    | '/date-format'
    | '/departments'
    | '/document-numbering'
    | '/email-templates'
    | '/exam-corrections'
    | '/exam-detail'
    | '/examinations'
    | '/fee-configuration'
    | '/fees'
    | '/governance-dashboard'
    | '/grading-scale'
    | '/learning-outcomes'
    | '/lesson-plans'
    | '/login'
    | '/menu'
    | '/notification-settings'
    | '/period-structure-setup'
    | '/promotion-rules'
    | '/report-config'
    | '/report-config-edit'
    | '/report-viewer'
    | '/reports'
    | '/reports-classic'
    | '/role-menu'
    | '/role-permissions'
    | '/roles'
    | '/school-calendar'
    | '/schools'
    | '/settings'
    | '/setup'
    | '/staff-setup'
    | '/student-add'
    | '/student-detail'
    | '/student-edit'
    | '/student-id-config'
    | '/student-life-development'
    | '/students'
    | '/subject-allocation'
    | '/subjects-curriculum'
    | '/subscriptions'
    | '/substitute-teacher-pool'
    | '/syllabus-tracker'
    | '/teacher-workload'
    | '/tenant-form'
    | '/tenant-role-menu'
    | '/tenants'
    | '/timetable'
    | '/timetable-config'
    | '/year-rollover'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-calendar'
    | '/academic-coordinator-dashboard'
    | '/academic-health-dashboard'
    | '/academic-policy-settings'
    | '/academics'
    | '/admissions-application-form'
    | '/admissions-applications'
    | '/admissions-inquiries'
    | '/admissions-inquiry-form'
    | '/admissions-tests'
    | '/akira-user-list'
    | '/attendance'
    | '/attendance-policy'
    | '/attendance-requests'
    | '/audit-logs'
    | '/calendar'
    | '/campus-setup'
    | '/class-teacher-allocation'
    | '/classes-sections'
    | '/communication-settings'
    | '/components'
    | '/curriculum-mapping'
    | '/dashboard'
    | '/date-format'
    | '/departments'
    | '/document-numbering'
    | '/email-templates'
    | '/exam-corrections'
    | '/exam-detail'
    | '/examinations'
    | '/fee-configuration'
    | '/fees'
    | '/governance-dashboard'
    | '/grading-scale'
    | '/learning-outcomes'
    | '/lesson-plans'
    | '/login'
    | '/menu'
    | '/notification-settings'
    | '/period-structure-setup'
    | '/promotion-rules'
    | '/report-config'
    | '/report-config-edit'
    | '/report-viewer'
    | '/reports'
    | '/reports-classic'
    | '/role-menu'
    | '/role-permissions'
    | '/roles'
    | '/school-calendar'
    | '/schools'
    | '/settings'
    | '/setup'
    | '/staff-setup'
    | '/student-add'
    | '/student-detail'
    | '/student-edit'
    | '/student-id-config'
    | '/student-life-development'
    | '/students'
    | '/subject-allocation'
    | '/subjects-curriculum'
    | '/subscriptions'
    | '/substitute-teacher-pool'
    | '/syllabus-tracker'
    | '/teacher-workload'
    | '/tenant-form'
    | '/tenant-role-menu'
    | '/tenants'
    | '/timetable'
    | '/timetable-config'
    | '/year-rollover'
  id:
    | '__root__'
    | '/'
    | '/academic-calendar'
    | '/academic-coordinator-dashboard'
    | '/academic-health-dashboard'
    | '/academic-policy-settings'
    | '/academics'
    | '/admissions-application-form'
    | '/admissions-applications'
    | '/admissions-inquiries'
    | '/admissions-inquiry-form'
    | '/admissions-tests'
    | '/akira-user-list'
    | '/attendance'
    | '/attendance-policy'
    | '/attendance-requests'
    | '/audit-logs'
    | '/calendar'
    | '/campus-setup'
    | '/class-teacher-allocation'
    | '/classes-sections'
    | '/communication-settings'
    | '/components'
    | '/curriculum-mapping'
    | '/dashboard'
    | '/date-format'
    | '/departments'
    | '/document-numbering'
    | '/email-templates'
    | '/exam-corrections'
    | '/exam-detail'
    | '/examinations'
    | '/fee-configuration'
    | '/fees'
    | '/governance-dashboard'
    | '/grading-scale'
    | '/learning-outcomes'
    | '/lesson-plans'
    | '/login'
    | '/menu'
    | '/notification-settings'
    | '/period-structure-setup'
    | '/promotion-rules'
    | '/report-config'
    | '/report-config-edit'
    | '/report-viewer'
    | '/reports'
    | '/reports-classic'
    | '/role-menu'
    | '/role-permissions'
    | '/roles'
    | '/school-calendar'
    | '/schools'
    | '/settings'
    | '/setup'
    | '/staff-setup'
    | '/student-add'
    | '/student-detail'
    | '/student-edit'
    | '/student-id-config'
    | '/student-life-development'
    | '/students'
    | '/subject-allocation'
    | '/subjects-curriculum'
    | '/subscriptions'
    | '/substitute-teacher-pool'
    | '/syllabus-tracker'
    | '/teacher-workload'
    | '/tenant-form'
    | '/tenant-role-menu'
    | '/tenants'
    | '/timetable'
    | '/timetable-config'
    | '/year-rollover'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AcademicCoordinatorDashboardRoute: typeof AcademicCoordinatorDashboardRoute
  AcademicHealthDashboardRoute: typeof AcademicHealthDashboardRoute
  AcademicPolicySettingsRoute: typeof AcademicPolicySettingsRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsApplicationFormRoute: typeof AdmissionsApplicationFormRoute
  AdmissionsApplicationsRoute: typeof AdmissionsApplicationsRoute
  AdmissionsInquiriesRoute: typeof AdmissionsInquiriesRoute
  AdmissionsInquiryFormRoute: typeof AdmissionsInquiryFormRoute
  AdmissionsTestsRoute: typeof AdmissionsTestsRoute
  AkiraUserListRoute: typeof AkiraUserListRoute
  AttendanceRoute: typeof AttendanceRoute
  AttendancePolicyRoute: typeof AttendancePolicyRoute
  AttendanceRequestsRoute: typeof AttendanceRequestsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CalendarRoute: typeof CalendarRoute
  CampusSetupRoute: typeof CampusSetupRoute
  ClassTeacherAllocationRoute: typeof ClassTeacherAllocationRoute
  ClassesSectionsRoute: typeof ClassesSectionsRoute
  CommunicationSettingsRoute: typeof CommunicationSettingsRoute
  ComponentsRoute: typeof ComponentsRoute
  CurriculumMappingRoute: typeof CurriculumMappingRoute
  DashboardRoute: typeof DashboardRoute
  DateFormatRoute: typeof DateFormatRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DocumentNumberingRoute: typeof DocumentNumberingRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  ExamCorrectionsRoute: typeof ExamCorrectionsRoute
  ExamDetailRoute: typeof ExamDetailRoute
  ExaminationsRoute: typeof ExaminationsRoute
  FeeConfigurationRoute: typeof FeeConfigurationRoute
  FeesRoute: typeof FeesRoute
  GovernanceDashboardRoute: typeof GovernanceDashboardRoute
  GradingScaleRoute: typeof GradingScaleRoute
  LearningOutcomesRoute: typeof LearningOutcomesRoute
  LessonPlansRoute: typeof LessonPlansRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  PeriodStructureSetupRoute: typeof PeriodStructureSetupRoute
  PromotionRulesRoute: typeof PromotionRulesRoute
  ReportConfigRoute: typeof ReportConfigRoute
  ReportConfigEditRoute: typeof ReportConfigEditRoute
  ReportViewerRoute: typeof ReportViewerRoute
  ReportsRoute: typeof ReportsRoute
  ReportsClassicRoute: typeof ReportsClassicRoute
  RoleMenuRoute: typeof RoleMenuRoute
  RolePermissionsRoute: typeof RolePermissionsRoute
  RolesRoute: typeof RolesRoute
  SchoolCalendarRoute: typeof SchoolCalendarRoute
  SchoolsRoute: typeof SchoolsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  StaffSetupRoute: typeof StaffSetupRoute
  StudentAddRoute: typeof StudentAddRoute
  StudentDetailRoute: typeof StudentDetailRoute
  StudentEditRoute: typeof StudentEditRoute
  StudentIdConfigRoute: typeof StudentIdConfigRoute
  StudentLifeDevelopmentRoute: typeof StudentLifeDevelopmentRoute
  StudentsRoute: typeof StudentsRoute
  SubjectAllocationRoute: typeof SubjectAllocationRoute
  SubjectsCurriculumRoute: typeof SubjectsCurriculumRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SubstituteTeacherPoolRoute: typeof SubstituteTeacherPoolRoute
  SyllabusTrackerRoute: typeof SyllabusTrackerRoute
  TeacherWorkloadRoute: typeof TeacherWorkloadRoute
  TenantFormRoute: typeof TenantFormRoute
  TenantRoleMenuRoute: typeof TenantRoleMenuRoute
  TenantsRoute: typeof TenantsRoute
  TimetableRoute: typeof TimetableRoute
  TimetableConfigRoute: typeof TimetableConfigRoute
  YearRolloverRoute: typeof YearRolloverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/year-rollover': {
      id: '/year-rollover'
      path: '/year-rollover'
      fullPath: '/year-rollover'
      preLoaderRoute: typeof YearRolloverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable-config': {
      id: '/timetable-config'
      path: '/timetable-config'
      fullPath: '/timetable-config'
      preLoaderRoute: typeof TimetableConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-role-menu': {
      id: '/tenant-role-menu'
      path: '/tenant-role-menu'
      fullPath: '/tenant-role-menu'
      preLoaderRoute: typeof TenantRoleMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-form': {
      id: '/tenant-form'
      path: '/tenant-form'
      fullPath: '/tenant-form'
      preLoaderRoute: typeof TenantFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-workload': {
      id: '/teacher-workload'
      path: '/teacher-workload'
      fullPath: '/teacher-workload'
      preLoaderRoute: typeof TeacherWorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus-tracker': {
      id: '/syllabus-tracker'
      path: '/syllabus-tracker'
      fullPath: '/syllabus-tracker'
      preLoaderRoute: typeof SyllabusTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substitute-teacher-pool': {
      id: '/substitute-teacher-pool'
      path: '/substitute-teacher-pool'
      fullPath: '/substitute-teacher-pool'
      preLoaderRoute: typeof SubstituteTeacherPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects-curriculum': {
      id: '/subjects-curriculum'
      path: '/subjects-curriculum'
      fullPath: '/subjects-curriculum'
      preLoaderRoute: typeof SubjectsCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject-allocation': {
      id: '/subject-allocation'
      path: '/subject-allocation'
      fullPath: '/subject-allocation'
      preLoaderRoute: typeof SubjectAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life-development': {
      id: '/student-life-development'
      path: '/student-life-development'
      fullPath: '/student-life-development'
      preLoaderRoute: typeof StudentLifeDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-id-config': {
      id: '/student-id-config'
      path: '/student-id-config'
      fullPath: '/student-id-config'
      preLoaderRoute: typeof StudentIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-edit': {
      id: '/student-edit'
      path: '/student-edit'
      fullPath: '/student-edit'
      preLoaderRoute: typeof StudentEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-detail': {
      id: '/student-detail'
      path: '/student-detail'
      fullPath: '/student-detail'
      preLoaderRoute: typeof StudentDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-add': {
      id: '/student-add'
      path: '/student-add'
      fullPath: '/student-add'
      preLoaderRoute: typeof StudentAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-setup': {
      id: '/staff-setup'
      path: '/staff-setup'
      fullPath: '/staff-setup'
      preLoaderRoute: typeof StaffSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-calendar': {
      id: '/school-calendar'
      path: '/school-calendar'
      fullPath: '/school-calendar'
      preLoaderRoute: typeof SchoolCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-permissions': {
      id: '/role-permissions'
      path: '/role-permissions'
      fullPath: '/role-permissions'
      preLoaderRoute: typeof RolePermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-menu': {
      id: '/role-menu'
      path: '/role-menu'
      fullPath: '/role-menu'
      preLoaderRoute: typeof RoleMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports-classic': {
      id: '/reports-classic'
      path: '/reports-classic'
      fullPath: '/reports-classic'
      preLoaderRoute: typeof ReportsClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-viewer': {
      id: '/report-viewer'
      path: '/report-viewer'
      fullPath: '/report-viewer'
      preLoaderRoute: typeof ReportViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-config-edit': {
      id: '/report-config-edit'
      path: '/report-config-edit'
      fullPath: '/report-config-edit'
      preLoaderRoute: typeof ReportConfigEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-config': {
      id: '/report-config'
      path: '/report-config'
      fullPath: '/report-config'
      preLoaderRoute: typeof ReportConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion-rules': {
      id: '/promotion-rules'
      path: '/promotion-rules'
      fullPath: '/promotion-rules'
      preLoaderRoute: typeof PromotionRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/period-structure-setup': {
      id: '/period-structure-setup'
      path: '/period-structure-setup'
      fullPath: '/period-structure-setup'
      preLoaderRoute: typeof PeriodStructureSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-plans': {
      id: '/lesson-plans'
      path: '/lesson-plans'
      fullPath: '/lesson-plans'
      preLoaderRoute: typeof LessonPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-outcomes': {
      id: '/learning-outcomes'
      path: '/learning-outcomes'
      fullPath: '/learning-outcomes'
      preLoaderRoute: typeof LearningOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading-scale': {
      id: '/grading-scale'
      path: '/grading-scale'
      fullPath: '/grading-scale'
      preLoaderRoute: typeof GradingScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance-dashboard': {
      id: '/governance-dashboard'
      path: '/governance-dashboard'
      fullPath: '/governance-dashboard'
      preLoaderRoute: typeof GovernanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-configuration': {
      id: '/fee-configuration'
      path: '/fee-configuration'
      fullPath: '/fee-configuration'
      preLoaderRoute: typeof FeeConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations': {
      id: '/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof ExaminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-detail': {
      id: '/exam-detail'
      path: '/exam-detail'
      fullPath: '/exam-detail'
      preLoaderRoute: typeof ExamDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-corrections': {
      id: '/exam-corrections'
      path: '/exam-corrections'
      fullPath: '/exam-corrections'
      preLoaderRoute: typeof ExamCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-numbering': {
      id: '/document-numbering'
      path: '/document-numbering'
      fullPath: '/document-numbering'
      preLoaderRoute: typeof DocumentNumberingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-format': {
      id: '/date-format'
      path: '/date-format'
      fullPath: '/date-format'
      preLoaderRoute: typeof DateFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum-mapping': {
      id: '/curriculum-mapping'
      path: '/curriculum-mapping'
      fullPath: '/curriculum-mapping'
      preLoaderRoute: typeof CurriculumMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-settings': {
      id: '/communication-settings'
      path: '/communication-settings'
      fullPath: '/communication-settings'
      preLoaderRoute: typeof CommunicationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes-sections': {
      id: '/classes-sections'
      path: '/classes-sections'
      fullPath: '/classes-sections'
      preLoaderRoute: typeof ClassesSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-teacher-allocation': {
      id: '/class-teacher-allocation'
      path: '/class-teacher-allocation'
      fullPath: '/class-teacher-allocation'
      preLoaderRoute: typeof ClassTeacherAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-setup': {
      id: '/campus-setup'
      path: '/campus-setup'
      fullPath: '/campus-setup'
      preLoaderRoute: typeof CampusSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-requests': {
      id: '/attendance-requests'
      path: '/attendance-requests'
      fullPath: '/attendance-requests'
      preLoaderRoute: typeof AttendanceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-policy': {
      id: '/attendance-policy'
      path: '/attendance-policy'
      fullPath: '/attendance-policy'
      preLoaderRoute: typeof AttendancePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akira-user-list': {
      id: '/akira-user-list'
      path: '/akira-user-list'
      fullPath: '/akira-user-list'
      preLoaderRoute: typeof AkiraUserListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions-tests': {
      id: '/admissions-tests'
      path: '/admissions-tests'
      fullPath: '/admissions-tests'
      preLoaderRoute: typeof AdmissionsTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions-inquiry-form': {
      id: '/admissions-inquiry-form'
      path: '/admissions-inquiry-form'
      fullPath: '/admissions-inquiry-form'
      preLoaderRoute: typeof AdmissionsInquiryFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions-inquiries': {
      id: '/admissions-inquiries'
      path: '/admissions-inquiries'
      fullPath: '/admissions-inquiries'
      preLoaderRoute: typeof AdmissionsInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions-applications': {
      id: '/admissions-applications'
      path: '/admissions-applications'
      fullPath: '/admissions-applications'
      preLoaderRoute: typeof AdmissionsApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions-application-form': {
      id: '/admissions-application-form'
      path: '/admissions-application-form'
      fullPath: '/admissions-application-form'
      preLoaderRoute: typeof AdmissionsApplicationFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-policy-settings': {
      id: '/academic-policy-settings'
      path: '/academic-policy-settings'
      fullPath: '/academic-policy-settings'
      preLoaderRoute: typeof AcademicPolicySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-health-dashboard': {
      id: '/academic-health-dashboard'
      path: '/academic-health-dashboard'
      fullPath: '/academic-health-dashboard'
      preLoaderRoute: typeof AcademicHealthDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-coordinator-dashboard': {
      id: '/academic-coordinator-dashboard'
      path: '/academic-coordinator-dashboard'
      fullPath: '/academic-coordinator-dashboard'
      preLoaderRoute: typeof AcademicCoordinatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-calendar': {
      id: '/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AcademicCoordinatorDashboardRoute: AcademicCoordinatorDashboardRoute,
  AcademicHealthDashboardRoute: AcademicHealthDashboardRoute,
  AcademicPolicySettingsRoute: AcademicPolicySettingsRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsApplicationFormRoute: AdmissionsApplicationFormRoute,
  AdmissionsApplicationsRoute: AdmissionsApplicationsRoute,
  AdmissionsInquiriesRoute: AdmissionsInquiriesRoute,
  AdmissionsInquiryFormRoute: AdmissionsInquiryFormRoute,
  AdmissionsTestsRoute: AdmissionsTestsRoute,
  AkiraUserListRoute: AkiraUserListRoute,
  AttendanceRoute: AttendanceRoute,
  AttendancePolicyRoute: AttendancePolicyRoute,
  AttendanceRequestsRoute: AttendanceRequestsRoute,
  AuditLogsRoute: AuditLogsRoute,
  CalendarRoute: CalendarRoute,
  CampusSetupRoute: CampusSetupRoute,
  ClassTeacherAllocationRoute: ClassTeacherAllocationRoute,
  ClassesSectionsRoute: ClassesSectionsRoute,
  CommunicationSettingsRoute: CommunicationSettingsRoute,
  ComponentsRoute: ComponentsRoute,
  CurriculumMappingRoute: CurriculumMappingRoute,
  DashboardRoute: DashboardRoute,
  DateFormatRoute: DateFormatRoute,
  DepartmentsRoute: DepartmentsRoute,
  DocumentNumberingRoute: DocumentNumberingRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  ExamCorrectionsRoute: ExamCorrectionsRoute,
  ExamDetailRoute: ExamDetailRoute,
  ExaminationsRoute: ExaminationsRoute,
  FeeConfigurationRoute: FeeConfigurationRoute,
  FeesRoute: FeesRoute,
  GovernanceDashboardRoute: GovernanceDashboardRoute,
  GradingScaleRoute: GradingScaleRoute,
  LearningOutcomesRoute: LearningOutcomesRoute,
  LessonPlansRoute: LessonPlansRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  PeriodStructureSetupRoute: PeriodStructureSetupRoute,
  PromotionRulesRoute: PromotionRulesRoute,
  ReportConfigRoute: ReportConfigRoute,
  ReportConfigEditRoute: ReportConfigEditRoute,
  ReportViewerRoute: ReportViewerRoute,
  ReportsRoute: ReportsRoute,
  ReportsClassicRoute: ReportsClassicRoute,
  RoleMenuRoute: RoleMenuRoute,
  RolePermissionsRoute: RolePermissionsRoute,
  RolesRoute: RolesRoute,
  SchoolCalendarRoute: SchoolCalendarRoute,
  SchoolsRoute: SchoolsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  StaffSetupRoute: StaffSetupRoute,
  StudentAddRoute: StudentAddRoute,
  StudentDetailRoute: StudentDetailRoute,
  StudentEditRoute: StudentEditRoute,
  StudentIdConfigRoute: StudentIdConfigRoute,
  StudentLifeDevelopmentRoute: StudentLifeDevelopmentRoute,
  StudentsRoute: StudentsRoute,
  SubjectAllocationRoute: SubjectAllocationRoute,
  SubjectsCurriculumRoute: SubjectsCurriculumRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SubstituteTeacherPoolRoute: SubstituteTeacherPoolRoute,
  SyllabusTrackerRoute: SyllabusTrackerRoute,
  TeacherWorkloadRoute: TeacherWorkloadRoute,
  TenantFormRoute: TenantFormRoute,
  TenantRoleMenuRoute: TenantRoleMenuRoute,
  TenantsRoute: TenantsRoute,
  TimetableRoute: TimetableRoute,
  TimetableConfigRoute: TimetableConfigRoute,
  YearRolloverRoute: YearRolloverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
